# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"clean_metadata": "00_movies_metadata.ipynb",
         "get_adult_feature": "00_movies_metadata.ipynb",
         "get_genre_names": "00_movies_metadata.ipynb",
         "labelEncoder_genres": "00_movies_metadata.ipynb",
         "get_original_language": "00_movies_metadata.ipynb",
         "get_numerical_features": "00_movies_metadata.ipynb",
         "get_datetime": "00_movies_metadata.ipynb",
         "get_datetime_decade_label": "00_movies_metadata.ipynb",
         "get_datetime_recent": "00_movies_metadata.ipynb",
         "lemmatize_stemming": "00_movies_metadata.ipynb",
         "preprocess": "00_movies_metadata.ipynb",
         "encode_movie_overview": "00_movies_metadata.ipynb",
         "get_movie_features": "00_movies_metadata.ipynb",
         "add_labels": "01_users.ipynb"}

modules = ["movies_metadata.py",
           "users.py"]

doc_url = "https://Hassan.github.io/movierecommender/"

git_url = "https://github.com/Hassan/movierecommender/tree/master/"

def custom_doc_links(name): return None
