# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['get_adult_feature', 'get_genre_names', 'labelEncoder_genres']

# Cell
def get_adult_feature(df):
    """Cleans the adult column by turning it into boolean. Uses False as default value for others."""
    return df.adult.map({'True': True, 'False': False}).fillna(False).astype(bool)

# Cell
def get_genre_names(df):
    """Returns list of genre Names per movie"""
    accepted_genres =
    return df.genres.apply(lambda x: [e['name'] for e in eval(x)])

# Cell
def labelEncoder_genres(meta_df):
    """Create label encoder object from genres"""

    genre_names = np.unique(np.concatenate(get_genre_names(meta_df).values).ravel())

    le = preprocessing.LabelEncoder()
    le.fit(genre_names.tolist())

    return le