# AUTOGENERATED! DO NOT EDIT! File to edit: 01_users.ipynb (unless otherwise specified).

__all__ = ['add_labels']

# Cell
import numpy as np
import pandas as pd
from IPython.display import HTML, Image
import os
from sklearn import preprocessing, dummy, metrics, ensemble
from sklearn.model_selection import cross_validate

import keras.models as kmodels
import keras.layers as klayers
import keras.backend as K
import keras

# Cell
def add_labels(df):
    """Adds labels to user and movie ids to be sequential"""
    df = df.copy()

    user_le = preprocessing.LabelEncoder()
    user_labels = user_le.fit_transform(df['userId'])

    df['user_label'] = user_labels

    movie_le = preprocessing.LabelEncoder()
    movie_labels = user_le.fit_transform(df['movieId'])

    df['movie_label'] = movie_labels

    return df, user_le, movie_labels